# Documentation generator script

def generate_docs():
    with open('README.md', 'w') as f:
        f.write('# Project Documentation\n')
        f.write('This documentation was generated by Python.\n')

if __name__ == "__main__":
    generate_docs()
